#!/bin/bash
#
# Auxiliary script used to configure environment variables 
#
# Author: Daniel Dias (dbdias at ime.usp.br)

echo Updating environment variables

#Program root dir
ROOT_DIR=/home/daniel/workspaces/java/mestrado/mdp-ip

#Directory where the problems are located
PROBLEM_DIR=$ROOT_DIR/problemsMDPIP

#Directory where any report generated by the program will be stored
REPORTS_DIR=$ROOT_DIR/reportsMDPIP

#Java execution parameters
BINARIES_DIR=$ROOT_DIR/bin
CLASSPATH=$ROOT_DIR:./libs/grappa1_4.jar
